### ISSUE TITLE
Addressing deprecated Pillow function usage in shavis

### ISSUE THREAD

**Issue by StrixzIV** [kernel137/sha256vis#1]
Hi, when I'm running the `shavis.py` I've encounter some DeprecationWarning that raises from the script like this:

```
DeprecationWarning: NEAREST is deprecated and will be removed in Pillow 10 (2023-07-01). 
Use Resampling.NEAREST or Dither.NONE instead.
```

Upon investigating, I've discovered that your script are using `Image.resize()` function with the resampling mode of `Image.NEAREST` which will be deprecated in Pillow 10.

I'm forking and working on the problem now. Hope you like my solution!

**Comment by kernel137** [comment]
Thank you for noticing! I merged the changes and will now fix all errors occurring from your changes. Your changes were really helpful! Thank you!
